### ISSUE TITLE
OC-tool -r command fails during downloading/unzipping

### ISSUE THREAD

**Issue by lignicolos** [rusty-bits/OC-tool#24] opened 2020-04-05 14:23 UTC
Hello, I'm running OC-tool using the -r switch to build the release versions. The tool fails sometime during the download/unzipping process. I've attached the tool.log file as well as a screenshot from my terminal window.

Running with -tr results in the same failure.

Running without the -r switch completes successfully.

[tool.log](https://github.com/rusty-bits/OC-tool/files/4433961/tool.log)
![Screen Shot 2020-04-05 at 10 14 16 AM](https://user-images.githubusercontent.com/27593909/78500879-0c2e1d00-7727-11ea-9045-57f5a3f79426.png)

**Comment by rusty-bits** [comment] 2020-04-06 01:17
I'm unable to reproduce the problem on this end  
could you try `./OC-tool -ir ./Docs/Config056.plist`  
and maybe a `./OC-tool -X` if that doesn't work  

something else that might help is the output of  
`./OC-tool -Dr`

**Comment by lignicolos** [comment] 2020-04-06 01:29
So I ran the tool with -Xr and it seems to die on my machine when trying to download the release version of the RealtekRTL8111.kext.

I also attached the output when I run it with -Dr.

Using /Users/josh/Hackintosh/OC-tool/INPUT/config.plist

 *** WARNING: -X option used ****************************************
 *** /Users/josh/Hackintosh/OC-tool/resources/prebuiltRelease has been removed
 *** the -X option is only useful if there is an issue with the
 *** previously downloaded resources causing problems while building.
 *** Using it at any other time will only increase bandwith usage and
 *** compile time, in many cases requiring all tools to be rebuilt.
 *********************************************************************

Downloading/unzipping needed or updated resources
Downloading OpenCore-0.5.6-RELEASE.zip ... unzipping ... done
Downloading Lilu-1.4.2-RELEASE.zip ... unzipping ... done
Downloading VirtualSMC-1.1.1-RELEASE.zip ... unzipping ... done
Downloading WhateverGreen-1.3.7-RELEASE.zip ... unzipping ... done
Downloading AppleALC-1.4.7-RELEASE.zip ... unzipping ... done
Downloading NVMeFix-1.0.1-RELEASE.zip ... unzipping ... done
Downloading  ...


when I ran it with just the -X option I got the output below and a successful build.

 *** WARNING: -X option used ****************************************
 *** /Users/josh/Hackintosh/OC-tool/resources/prebuiltRelease has been removed
 *** the -X option is only useful if there is an issue with the
 *** previously downloaded resources causing problems while building.
 *** Using it at any other time will only increase bandwith usage and
 *** compile time, in many cases requiring all tools to be rebuilt.
 *********************************************************************

Downloading/unzipping needed or updated resources
Downloading OpenCore-0.5.6-DEBUG.zip ... unzipping ... done
Downloading Lilu-1.4.2-DEBUG.zip ... unzipping ... done
Downloading VirtualSMC-1.1.1-DEBUG.zip ... unzipping ... done
Downloading WhateverGreen-1.3.7-DEBUG.zip ... unzipping ... done
Downloading AppleALC-1.4.7-DEBUG.zip ... unzipping ... done
Downloading NVMeFix-1.0.1-DEBUG.zip ... unzipping ... done
Downloading RealtekRTL8111
[Dr.log](https://github.com/rusty-bits/OC-tool/files/4435456/Dr.log)
-V2.2.2.zip ... unzipping ... done
Downloading AppleSupport-2.1.6-DEBUG.zip ... unzipping ... done
Downloading OpenCore-0.5.6-DEBUG.zip ... unzipping ... done
Downloading OpenCoreShell-1.0.4-DEBUG.zip ... unzipping ... done

Creating new /Users/josh/Hackintosh/OC-tool/OUTPUT/EFI ... done

**Comment by rusty-bits** [comment] 2020-04-06 02:04
found a missing ']' in the base git.repo.json file used to create .tool-files/git.repo.json.txt  
half the repo was pointing at nothing

should be fixed, try it again when you can

**Closed** 2020-04-07 00:44 UTC
